---
title: "C-model-comparisons"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{C-model-comparisons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(surveyIndex)
```


```{r regular_gams}


# data wrangle -----------------------------------------------------------------

# SRVY <- c("EBS")
SPP <- c(# must match common name column
  # "arrowtooth flounder",
  # "Pacific cod",
  "walleye pollock",
  "yellowfin sole",
  "red king crab")
yrs <- 1995:2021
SRVY <- "EBS"

i <- 1

# yearS <- c(2010, 2017, 2019, 2021) #1995:2021
crs_latlon = "+proj=longlat +datum=WGS84"
# crs_proj = "+proj=aea +lat_1=57 +lat_2=63 +lat_0=59 +lon_0=-170 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
crs_proj = "EPSG:3338"


public_data <- dat <- surveyIndex::noaa_afsc_public_foss 

crs_latlon = "+proj=longlat +datum=WGS84"
crs_proj = "EPSG:3338"

ll <- surveyIndex::convert_crs(x = public_data$longitude_dd,
                 y = public_data$latitude_dd, 
                 crs_in = crs_latlon, 
                 crs_out = crs_proj)  

# Get cold pool data using cold pool data from the {coldpool} R package
dat <- dat %>%
  dplyr::mutate(lon = ll$X,
                lat = ll$Y,
                sx = ((longitude_dd - mean(longitude_dd, na.rm = TRUE))/1000),
                sy = ((latitude_dd - mean(latitude_dd, na.rm = TRUE))/1000)) %>% 
  stats::na.omit() %>% 
  dplyr::filter(common_name == SPP[i] &
                  year %in% yrs &
                  srvy %in% SRVY)

method <- "ML"
knotsP <- 376

# model ------------------------------------------------------------------------


# null spatial model
b1 <- gam(cpue_kgha~s(sx,sy,bs=c('ts'),k=376), 
          data = dat, family = tw, gamma = 1.4)

# null temporal model
b2 <- gam(cpue_kgha ~ year, 
          data=dat, family = tw, gamma = 1.4, method = method)

# null spatiotemporal model
b3 <- gam(cpue_kgha ~ year + s(sx,sy,bs=c('ts'),k=376), 
          data=dat, family = tw, gamma = 1.4, method = method)

# null covariate temperature model
b4 <- gam(cpue_kgha ~ #year + s(sx,sy,bs=c('ts'),k=376) + 
            # s(depth_m,bs='ts',k=10) +
            s(log(bottom_temperature_c+3),bs='ts',k=10), 
          data=dat, family = tw, gamma = 1.4, method = method)

# null covariate depth model
b5 <- gam(cpue_kgha ~ #year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10),# + 
            # s(log(bottom_temperature_c+3),bs='ts',k=10),  
          data=dat, family = tw, gamma = 1.4, method = method)

# null covariate model
b6 <- gam(cpue_kgha ~ #year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10) + 
          s(log(bottom_temperature_c+3),bs='ts',k=10),
          data=dat, family = tw, gamma = 1.4, method = method)

# full model
b7 <- gam(cpue_kgha ~ year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10) + 
            s(log(bottom_temperature_c+3),bs='ts',k=10),
          data=dat, family = tw, gamma = 1.4, method = method)

# full model with ship effect
b8 <- gam(cpue_kgha ~ year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10) + 
            s(log(bottom_temperature_c+3),bs='ts',k=10) + 
            vessel_id,
          data=dat, family = tw, gamma = 1.4, method = method)

# full model with year fixed effect (right?)
b9 <- gam(cpue_kgha ~ year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10) + 
            s(log(bottom_temperature_c+3),bs='ts',k=10) + 
            s(sx,sy,bs=c('ts'),k=50,by=year,id=1),
          data=dat, family = tw, gamma = 1.4, method = method)

# full model with year fixed effect (right?) and vessel
b10 <- gam(cpue_kgha ~ year + s(sx,sy,bs=c('ts'),k=376) + 
            s(depth_m,bs='ts',k=10) + 
            s(log(bottom_temperature_c+3),bs='ts',k=10) + 
            vessel_id + 
            s(sx,sy,bs=c('ts'),k=50,by=year,id=1),
          data=dat, family = tw, gamma = 1.4, method = method)

b <- AIC(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10)# get(paste0("b", 1:9))

save(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, file = "./output/basic_gams.rdata")

bb <- get(rownames(b)[b$AIC %in% min(b$AIC):(min(b$AIC)+5)])
# b$df %in% min(b$df):(min(b$df)+5) 

par(mfrow = c(2,3))
gam.check(bb)
vis.gam(bb)

cc <- predict.gam(object = bb, newdata = dat[dat$year == 2021,])

dat0 <- dat[dat$year == 2021,] %>% 
  dplyr::mutate(pred = cc)

figure <- ggplot() +
  geom_point(data = dat0, 
             mapping = aes(x= longitude_dd, y = latitude_dd, color = pred))

```
