---
title: "Comparing tinyVAST to GAM-based indices"
date: "`r format(Sys.Date(), format='%B %d %Y') `"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tinyVAST vs GAMs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, message=FALSE, error=FALSE, warning = FALSE, 
  comment = "#>"
)

# Index and mapping 
library(sdmgamindex) 
library(dplyr)
library(sf)
library(gstat)
library(raster)
library(akgfmaps)  # devtools::install_github("afsc-gap-products/akgfmaps", build_vignettes = TRUE)
library(coldpool) # devtools::install_github("afsc-gap-products/coldpool")
  
# VAST tools
library(tinyVAST) #devtools::install_github("vast-lib/tinyVAST", dependencies = TRUE)
library(fmesher) # for making pred meshes for tinyVAST

# Aesthetics
options(ggplot2.continuous.colour = "viridis")
options(ggplot2.continuous.fill = "viridis")
theme_set(theme_bw())
```

## Example stock: pollock in the Gulf of Alaska

For this vignette, we will fit a GAM-based index and a tinyVAST model to data for GOA Pacific ocean perch. 

### Load public catch data
```{r}
SPECIES <- c("Pacific ocean perch")
YEARS <- 2015:2023
nyrs <- length(YEARS)
SRVY <- "GOA"

# Public catch data
dat0 <- sdmgamindex::noaa_afsc_public_foss %>% 
  dplyr::filter(srvy == "GOA" &
                  year %in% YEARS &
                  common_name %in% SPECIES) %>%
  dplyr::mutate(hauljoin = paste0(stratum, "_", station, "_", date_time)) %>%
  dplyr::select(
    year, date_time, latitude_dd_start, longitude_dd_start,
    cpue_kgkm2, common_name, 
    bottom_temperature_c, depth_m, # covariates (used later)
    srvy, area_swept_km2, duration_hr, vessel_id, hauljoin
  )

head(dat0)
```
For tinyVAST, the data needs to be in a specific format. Let's format it properly:

```{r}
dat <- dat0 |>
  dplyr::rename('x' = longitude_dd_start,
                'y' = latitude_dd_start,
                'time' = year) |>
                dplyr::mutate(catch_kg = cpue_kgkm2 * area_swept_km2 #, 
                  #logn = log(catch_kg) # results in Infs
                  ) 
head(dat)
```

### Build prediction grid/mesh

```{r}
mesh <- fm_mesh_2d(dat[,c('x','y')])
plot(mesh)
```

### Fit model
```{r}
vastfit <- tinyVAST(formula = catch_kg ~ 0 + factor(time),
                    data = dat, dsem = NULL,
                    spatial_graph = mesh,
                    family = tweedie()
                    )
vastfit
```

### Get area-weighted total abundance
```{r}
integrate_output(object = vastfit,newdata = subset(dat,time==2015))
Est <- sapply(YEARS, 
              FUN = \(t) integrate_output, vastfit, newdata = subset(dat,time==t))
```

### Add predictions to `dat`

```{r}
#dat$catch_kg_pred <- predict(object = vastfit,newdata = )
```